# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Welcome to Farb's Blog"
weight = 1
[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "欢迎来到寒舍"
weight = 1
