# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/farb"

[social.params]
icon = "github"

[[social]]
identifier = "cnblogs"
name = "博客园"
url = "https://www.cnblogs.com/farb"

[social.params]
icon = "cnblogs"

[[social]]
identifier = "leetcode"
name = "力扣"
url = "https://leetcode.cn/u/int2147483647"

[social.params]
icon = "leetcode"

[[social]]
identifier = "gitee"
name = "Gitee"
url = "https://gitee.com/farb"

[social.params]
icon = "gitee"